import type { CardData } from "@/components/UI/card/types";

export const housingData: CardData[] = [
  {
    id: 1,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 2,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 3,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 4,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 5,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 6,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 7,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 8,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 9,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 10,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 11,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
  {
    id: 12,
    images: ["/src/assets/images/house.png"],
    price: 26,
    rating: 3.4,
    title: "Beautiful and picturesque house",
    address: "12 Morris Ave, Toronto",
    guests: 2,
  },
];
